"default": "not applicable"
"leave_requireds_blank": false
"study_specific_metadata":
  "host_type_specific_metadata":
    "sterile_water_blank":
      "default": "not applicable"
      "sample_type_specific_metadata":
        "control blank":
          "metadata_fields":
            dna_extracted:
              allowed:
                - "TRUE"
              default: "TRUE"
              type: string
            elevation:
              default: 193
              type: number
            geo_loc_name:
              allowed:
                - "USA:CA:San Diego"
              default: "USA:CA:San Diego"
              type: string
            latitude:
              default: 32.5
              type: number
            longitude:
              default: -117.25
              type: number
            physical_specimen_location:
              allowed:
                - "UCSD"
              default: "UCSD"
              type: string
            physical_specimen_remaining:
              allowed:
                - "FALSE"
              default: "FALSE"
              type: string
"metadata_transformers":
  "pre_transformers":
    collection_date:
      sources:
        - "collection_timestamp"
      function: "pass_through"
