"default": "not applicable"
"leave_requireds_blank": false
"study_start_date": "10/21/2008"
"study_specific_metadata":
  "host_type_specific_metadata":
    ebi_submittable:
      metadata_fields:
        country:
          allowed:
            - "USA"
          default: "USA"
          type: string
        dna_extracted:
          allowed:
            - 'TRUE'
          default: 'TRUE'
          type: string
        title:
          allowed:
            - "NPH"
          default: "NPH"
          type: string
        tube_id:
          empty: false
          field_desc: The identification of the tube containing the sample.
          is_phi: false
          required: true
          type: string
    "human":
      "default": "not provided"
      "metadata_fields":
        elevation:
          default: 0
          type: number
        geo_loc_name:
          allowed:
            - 'USA'
          default: 'USA'
          type: string
        host_height:
          allowed:
            - "not provided"
          default: "not provided"
          type: string
        host_weight:
          allowed:
            - "not provided"
          default: "not provided"
          type: string
        latitude:
          default: 40
          type: number
        longitude:
          default: -100
          type: number
        physical_specimen_location:
          allowed:
            - 'UCSD'
          default: "UCSD"
          type: string
        physical_specimen_remaining:
          allowed:
            - 'TRUE'
          default: 'TRUE'
          type: string
      "sample_type_specific_metadata":
        "feces":
          "metadata_fields":
            description:
              allowed:
                - "fecal sample"
              default: "fecal sample"
              type: string
            qiita_sample_type:
              allowed:
                - "feces"
              default: "feces"
              empty: false
              is_phi: false
              required: false
              type: string
    "sterile_water_blank":
      "default": "not applicable"
      "sample_type_specific_metadata":
        "control shield":
          "metadata_fields":
            description:
              allowed:
                - "control shield"
              default: "control shield"
              type: string
            elevation:
              default: 193
              type: number
            geo_loc_name:
              allowed:
                - "USA:CA:San Diego"
              default: "USA:CA:San Diego"
              type: string
            latitude:
              default: 32.5
              type: number
            longitude:
              default: -117.25
              type: number
            physical_specimen_location:
              allowed:
                - "UCSDMI"
              default: "UCSDMI"
              type: string
            physical_specimen_remaining:
              allowed:
                - "TRUE"
              default: "TRUE"
              type: string
"metadata_transformers":
  "pre_transformers":
    collection_date:
      sources:
        - "collection_date_time"
      function: "format_real_vs_blanks_dates"
    collection_timestamp:
      sources:
        - "collection_date_time"
      function: "format_real_vs_blanks_dates"
    "host_age":
      "sources":
        - "age"
      "function": "pass_through"
    host_body_mass_index:
      sources:
        - "bmi"
      function: "pass_through"
    host_life_stage:
      sources:
        - "age"
      function: "transform_age_to_life_stage"
    host_subject_id:
      sources:
        - "biobank_id"
      function: "pass_through"
    sex:
      sources:
        - "sex_at_birth"
      function: "transform_sex_at_birth_to_sex"
